apiVersion: v1
kind: Service
metadata:
  name: appointmentscheduling-service
spec:
  selector:
    app: appointmentscheduling
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
