apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: 442426890046.dkr.ecr.ap-southeast-1.amazonaws.com/notificationservice:latest
        ports:
        - containerPort: 8002
